changelog:
  exclude:
    authors:
      - dependabot
      - pre-commit-ci
  categories:
    - title: Bugs fixes 🐛
      labels:
        - bug
    - title: Features and enhancements 🎉
      labels:
        - enhancement
        - Qt6
        - UI
    - title: Tooling 🔧
      labels:
        - ci-cd
        - github_actions
        - packaging
        - tooling
    - title: documentation 📖
      labels:
        - Documentation
    - title: Other Changes
      labels:
        - "*"
