name: "🎳 Tester"

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - .github/workflows/tester.yml
      - requirements/testing.txt

  pull_request:
    branches:
      - master
    paths:
      - '**.py'
      - .github/workflows/tester.yml
      - requirements/testing.txt

env:
  PROJECT_FOLDER: "menu_from_project"
  PYTHON_VERSION: 3.9

jobs:
  tests-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          cache: "pip"
          cache-dependency-path: "requirements/testing.txt"
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U -r requirements/testing.txt

      - name: Run Unit tests
        run: pytest -p no:qgis tests/unit/

  test-qgis:
    runs-on: ubuntu-latest

    container:
      image: qgis/qgis:release-3_28
      env:
        CI: true
        DISPLAY: ":1"
        MUTE_LOGS: true
        NO_MODALS: 1
        PYTHONPATH: "/usr/share/qgis/python/plugins:/usr/share/qgis/python:."
        QT_QPA_PLATFORM: "offscreen"
        WITH_PYTHON_PEP: false
        options: -v /tmp/.X11-unix:/tmp/.X11-unix

    steps:
      - name: Get source code
        uses: actions/checkout@v5

      - name: Print QGIS version
        run: qgis --version

      - name: Install Python requirements
        run: |
          python3 -m pip install -U pip setuptools wheel
          python3 -m pip install -U -r requirements/testing.txt

      - name: Run Unit tests
        run: |
          Xvfb :1 &
          python3 -m pytest tests/qgis/
